Feat/82 add active attribute to couch
quouch/quouch pull request #93
Opened 2024-08-14 19:03 UTC by lisbethpurrucker

Issue number: resolves #82

---------

As a lot of our users are inactive and not responsive which increases frustration amongst our travellers, we needed to come up with a way of not displaying the couches without having to delete their profiles entirely.

Therefore, I decided to add an active attribute to the couch which I can manually update.

- Added active column to couches table through migration
- Added where statement to couches index query
- Added test
- Added line to couches fixture to set active attribute randomly (same default for every couch would not serve for testing)

## Other information

I could not test my test properly because `@couches` returned an empty relation so the test would pass in both cases. Due to the tests not running properly on my end, it seems like the fixtures are not created either. I checked in the test console if any couches are created, but `Couch.all` returned an empty array. I might miss something here.

### Checklist
- [x] Code compiles correctly
- [ ] Created tests which fail without the change (if possible)
- [ ] All tests passing
- [x] Rubocop passes

2024-08-14 19:16 UTC, lisbethpurrucker commented
@papotte again the tests are failing :( what did I dooo

2024-08-14 19:16 UTC, lisbethpurrucker commented
@papotte again the tests are failing :( why does it hate me

2024-08-15 08:53 UTC, papotte requested changes

2024-08-15 08:53 UTC, papotte commented on test/fixtures/couches.yml
> +  active: <%= [true, false].sample %>
Tests are failing because this statement makes them flaky. All the tests are assuming that all the couches created here are a match, so a total of 16 couches are expected to exist. 
The active attribute makes that an unknown number and a lot harder to test.
In fixtures, this value should be `true` always.

2024-08-15 08:53 UTC, papotte commented on test/controllers/concerns/couches_concern_test.rb
> +    index
```suggestion
    # Create a user with an inactive couch
    inactive_user = FactoryBot.create(:test_user_couch)
    inactive_user.couch.active = false
    inactive_user.couch.save!
    # Create one user with an active couch
    FactoryBot.create(:test_user_couch)

    index
    
    # we know that there's only one active couch!
    assert_equal 1, @pagy.count

```

2024-08-15 08:53 UTC, papotte commented on test/fixtures/couches.yml
> +  active: <%= [true, false].sample %>
Also, this fixture is not included in Unit Tests, only integration or systems test.

2024-08-15 13:41 UTC, papotte approved these changes

2024-08-15 13:54 UTC, merged